### ISSUE TITLE
CPU load 100% 

### ISSUE THREAD

**Issue by michaelfung** [jhthorsen/mojo-apns#10]
Hi Jan, 

Many thanks Jan for sharing this module.

The CPU load goes to 100% for a few seconds just by sending a single message to apple. I tried  latest Mojolicious v8.13, or v7.82, but all the same result. Could you look into this issue please?

Many thanks,
Michael

**Comment by michaelfung** [comment]
I found the **drain** callback is called repeatedly while the stream connection is alive, that caused 100% CPU load.

Not ideal workaround by disable the on drain subscription, and emit a 'sent' event after write to notify the send_p sub that we are done.

Any idea why the  **drain** callback is called repeatedly?

**Comment by jhthorsen** [comment]
No, I'm not sure why that happens. Can you write a short program/test that illustrate the issue?

**Comment by jhthorsen** [comment]
I'm going to close this, since the module is no longer available on CPAN and does not really work.
