### ISSUE TITLE
Distribution no longer available on CPAN?

### ISSUE THREAD

**Issue by leejo** [jhthorsen/mojo-apns#12]
Hey @jhthorsen - it seems the only version(s) of Mojo::APNS available on CPAN are now from BackPan, which means it's not going to install via the usual toolchain - any compelling reason for the removal?

**Comment by leejo** [comment]
Alright I see: https://github.com/jhthorsen/mojo-apns/issues/11#issuecomment-671717935 # @jhthorsen - you should put in a deprecated notice or adoptme on PAUSE and not be removing distributions from CPAN unless you have very compelling reasons. We're using this module in our stack, we can probably write around it/replace it, but removing it from CPAN because it's old is very poor form.

**Comment by leejo** [comment]
OK, I checked - we can trivially write around it - but my argument still stands.

**Comment by jhthorsen** [comment]
This module was removed almost a year ago, so I’m not sure if it’s worth my time to maintain it when it seems like you are the only user. I can understand it’s annoying, but I also think it’s risky to keep a unmaintained and non-working module on CPAN for years. (I actually feel bad I didn’t remove it earlier)

I’ll hand it over to you if you want to namespace! Just let me know 👍

**Comment by leejo** [comment]
@jhthorsen - no need, i've removed it from our stack. Thanks!
