### ISSUE TITLE
APNs based on the HTTP/2 

### ISSUE THREAD

**Issue by twocolors** [jhthorsen/mojo-apns#9]
Support network protocol HTTP/2

https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW1

**Comment by jhthorsen** [comment]
I don't support HTTP/2, since Mojolicious / Mojo::UserAgent does not support it and I don't know how to implement it.
